// Copyright (c) 2018, Bitlitas
// All rights reserved. Based on Cryptonote and Monero.

#pragma  once 

#define CORE_RPC_ERROR_CODE_WRONG_PARAM           -1
#define CORE_RPC_ERROR_CODE_TOO_BIG_HEIGHT        -2
#define CORE_RPC_ERROR_CODE_TOO_BIG_RESERVE_SIZE  -3
#define CORE_RPC_ERROR_CODE_WRONG_WALLET_ADDRESS  -4
#define CORE_RPC_ERROR_CODE_INTERNAL_ERROR        -5
#define CORE_RPC_ERROR_CODE_WRONG_BLOCKBLOB       -6
#define CORE_RPC_ERROR_CODE_BLOCK_NOT_ACCEPTED    -7
#define CORE_RPC_ERROR_CODE_CORE_BUSY             -9
#define CORE_RPC_ERROR_CODE_WRONG_BLOCKBLOB_SIZE  -10
#define CORE_RPC_ERROR_CODE_UNSUPPORTED_RPC       -11
#define CORE_RPC_ERROR_CODE_MINING_TO_SUBADDRESS  -12


