#!/bin/bash

# Copyright (c) 2018, Bitlitas
# All rights reserved. Based on Cryptonote and Monero.

case $1 in
   config)
        cat <<'EOM'
graph_title difficulty
graph_vlabel difficulty
graph_category bitlitas
difficulty.label difficulty
EOM
        exit 0;;
esac

printf "difficulty.value "
# rewrite using curl or similar: /home/user/bitlitas/build/release/src/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep difficulty | cut -d ' ' -f2
