#!/bin/bash

# Copyright (c) 2018, Bitlitas
# All rights reserved. Based on Cryptonote and Monero.

case $1 in
   config)
        cat <<'EOM'
graph_title outgoing_connections_count
graph_vlabel outgoing_connections_count
graph_category bitlitas
outgoing_connections_count.label outgoing_connections_count
EOM
        exit 0;;
esac

printf "outgoing_connections_count.value "
# rewrite using curl or similar: /home/user/bitlitas/build/release/src/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep outgoing_connections_count | cut -d ' ' -f2
