#!/bin/bash

# Copyright (c) 2018, Bitlitas
# All rights reserved. Based on Cryptonote and Monero.

case $1 in
   config)
        cat <<'EOM'
graph_title tx_pool_size
graph_vlabel tx_pool_size
graph_category bitlitas
tx_pool_size.label tx_pool_size
EOM
        exit 0;;
esac

printf "tx_pool_size.value "
# rewrite using curl or similar: /home/user/bitlitas/build/release/src/connectivity_tool --ip=127.0.0.1 --rpc_port=8081 --timeout=1000 --rpc_get_daemon_info | grep tx_pool_size| cut -d ' ' -f2
